const $ = (q) => document.querySelector(q);
const tabs = [...document.querySelectorAll('[role="tab"]')];
function activateTab(name,focus=false){tabs.forEach(tab=>{const active=tab.dataset.tab===name;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;$('#panel-'+tab.dataset.tab).hidden=!active;if(active&&focus)tab.focus();});}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>activateTab(tab.dataset.tab));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(index+1)%tabs.length;if(e.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();activateTab(tabs[next].dataset.tab,true);}});});
$('.menu').addEventListener('click',()=>{const open=$('nav').classList.toggle('open');$('.menu').setAttribute('aria-expanded',String(open));});
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{$('nav').classList.remove('open');$('.menu').setAttribute('aria-expanded','false');}));
let route;
const calculatorUrl=(service='lcl',city='',quantity='')=>{const params=new URLSearchParams({service});if(city)params.set('city',city);if(quantity)params.set('quantity',quantity);return '/eastinter-pricing-calculator?'+params.toString();};
const destinationKeys={'Sydney, Australia':'sydney','Melbourne, Australia':'melbourne','Brisbane, Australia':'brisbane','Adelaide, Australia':'adelaide','Perth, Australia':'perth','Other Australian destination':'other'};
const methodKeys={'Sea freight':'lcl','Air freight':'bulkAir','Help me choose':'lcl'};
$('#quick-quote').addEventListener('submit',e=>{e.preventDefault();route=Object.fromEntries(new FormData(e.target));window.location.href=calculatorUrl(methodKeys[route.method]||'lcl',destinationKeys[route.destination]||'');});
$('.close').addEventListener('click',()=>$('#quote-dialog').close());
document.querySelectorAll('[data-service]').forEach(button=>button.addEventListener('click',()=>{window.location.href=calculatorUrl(methodKeys[button.dataset.service]||'lcl');}));
function makeMail(subject,body){return 'mailto:zzj@eastinter.net?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);}
$('#details-form').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const mail=makeMail('Freight quote: '+route.origin+' to '+route.destination,'Hello East Inter,\n\nPlease provide a freight quote.\n\nName: '+d.name+'\nEmail: '+d.email+'\nOrigin: '+route.origin+'\nDestination: '+route.destination+'\nMethod: '+route.method+'\nCargo: '+d.cargo+'\nTotal weight: '+d.weight+' kg\nTotal volume: '+(d.volume?d.volume+' CBM':'Not yet confirmed')+'\n\nPlease confirm costs, inclusions and estimated transit time.');$('#email-fallback').href=mail;$('#email-fallback').hidden=false;$('#quote-status').textContent='Your email is ready. Review and send it in your email app. If it does not open, use the link below or email zzj@eastinter.net.';window.location.href=mail;});
$('#track-form').addEventListener('submit',e=>{e.preventDefault();const ref=new FormData(e.target).get('reference').trim();if(!ref){e.target.elements.reference.setCustomValidity('Enter a shipment reference.');e.target.reportValidity();return;}const target=$('#track-result');target.replaceChildren();const a=document.createElement('a');a.href=makeMail('Shipment update: '+ref,'Hello East Inter,\n\nPlease share the latest status and expected delivery date for shipment '+ref+'.\n\nThank you.');a.textContent='Email our team about '+ref+' ↗';a.style.color='var(--blue)';target.append(a);});
$('#track-form input').addEventListener('input',e=>e.target.setCustomValidity(''));
function calculateVolume(length,width,height,quantity){if(![length,width,height,quantity].every(n=>Number.isFinite(n)&&n>0)||!Number.isInteger(quantity))throw new Error('Enter positive dimensions and a whole number of boxes.');const volume=length*width*height*quantity/1000000;if(!Number.isFinite(volume))throw new Error('These dimensions are too large.');return volume;}
$('#volume-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);try{const total=calculateVolume(...['length','width','height','quantity'].map(k=>Number(f.get(k))));window.location.href=calculatorUrl('lcl','',String(total));}catch(error){$('#volume-result').textContent=error.message;}});
$('#year').textContent=new Date().getFullYear();
const modelContext = document.modelContext || navigator.modelContext;
if(modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(modelContext.registerTool({name:'calculate_shipment_volume',annotations:{readOnlyHint:false,untrustedContentHint:false},description:'Calculate the total physical volume in cubic metres for identical shipment boxes. This does not calculate freight prices.',inputSchema:{type:'object',properties:{length_cm:{type:'number',exclusiveMinimum:0},width_cm:{type:'number',exclusiveMinimum:0},height_cm:{type:'number',exclusiveMinimum:0},boxes:{type:'integer',minimum:1}},required:['length_cm','width_cm','height_cm','boxes']},execute:async({length_cm,width_cm,height_cm,boxes})=>{const cbm=calculateVolume(length_cm,width_cm,height_cm,boxes);activateTab('volume');const form=$('#volume-form');for(const [name,value]of Object.entries({length:length_cm,width:width_cm,height:height_cm,quantity:boxes}))form.elements[name].value=value;$('#volume-result').textContent='Total volume: '+cbm.toLocaleString('en',{maximumSignificantDigits:8})+' CBM. Final chargeable volume is confirmed after warehouse measurement.';return{content:[{type:'text',text:JSON.stringify({cbm})}]};}}, {signal:lifecycle.signal})).catch(()=>{});}catch{}}
